# Hidden street : A dark place
sm.lockInGameUI(True)
sm.setPlayerAsSpeaker()
sm.sendNext("我在哪里？我差点就追上那个人了...")
sm.forcedInput(2)
sm.sendDelay(2000)
sm.sendNext("有人在吗..？")
sm.sendNext("听起来像是鹰眼的声音。")
sm.warpInstanceOut(913031003, 3)
sm.setQRValue(20891, "dream", False)
sm.lockInGameUI(False)
